name: flutter_fast_location_vaos1
description: "Projeto flutter UniSENAI localização rápida."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter  
  flutter_mobx: ^2.2.1+1
  hive_flutter: ^1.1.0
  map_launcher: ^3.3.0
  mobx: ^2.3.3+2
  path_provider: ^2.1.3
  path_provider_android: ^2.2.4
  path_provider_ios: ^2.0.11
  fast_location_vaos1: any
dio: ^4.0.6
flutter_mobx: ^2.0.4
mobx: ^2.0.6+1
hive: ^2.1.0
hive_flutter: ^1.1.0
path: ^1.8.0
path_provider: ^2.0.2
path_provider_android: ^2.0.14
path_provider_ios: ^2.0.9
map_launcher: ^2.2.1+1
geocoding: ^2.1.1
http: ^0.13.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
mobx_codegen: ^2.0.1+3
build_runner: ^2.0.5
hive_generator: ^2.0.0
lints: ^1.0.1   

flutter: 
  uses-material-design: true